using Dottest.Framework;
using NUnit.Framework;
using TrendViewer.Controller;

namespace TrendViewer.DotTest.Controller
{
    [TestFixture()]
    public class DataNotificaitonConstTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/r8ayg", "/GQPCw")]
        public void TestDataNotificaitonConstConstructor01()
        {
            DataNotificaitonConst dataNotificaitonConst = new DataNotificaitonConst();
        }

    }
}
