#ifndef STRING_DEFINITION
#define STRING_DEFINITION

#define AFX_IDS_APP_TITLE	"Plan Manager"
#define AFX_IDS_IDLEMESSAGE	"Ready"
#define AFX_IDS_PREVIEW_CLOSE	"Close print preview mode\nCancel Preview"
#define DS_PLAN_FLOW_DETAIL_TAB_LABEL	"Flow"
#define ID_INDICATOR_CAPS	"CAP"
#define ID_INDICATOR_EXT	"EXT"
#define ID_INDICATOR_NUM	"NUM"
#define ID_INDICATOR_OVR	"OVR"
#define ID_INDICATOR_PROGRESS	"progress here"
#define ID_INDICATOR_REC	"REC"
#define ID_INDICATOR_SCRL	"SCRL"
#define IDR_MAINFRAME	"Plan Manager"
#define IDR_PLAN_CONTROLLER	"Plan Controller"
#define IDR_PLAN_EDITOR	"Plan Editor"
#define IDS_ACTIVE_PLAN_LIST_ACTIVATION_COLUMN	"Activation"
#define IDS_ACTIVE_PLAN_LIST_CATEGORY_COLUMN	"Category"
#define IDS_ACTIVE_PLAN_LIST_INSTANCE_COLUMN	"Instance"
#define IDS_ACTIVE_PLAN_LIST_LOCATION_COLUMN	"Location"
#define IDS_ACTIVE_PLAN_LIST_OWNER_COLUMN	"Owner"
#define IDS_ACTIVE_PLAN_LIST_PLAN_COLUMN	"Plan"
#define IDS_ACTIVE_PLAN_LIST_REMARKS_COLUMN	"Remarks"
#define IDS_ACTIVE_PLAN_LIST_STATE_COLUMN	"State"
#define IDS_ACTIVE_PLAN_LIST_STEP_COLUMN	"Step"
#define IDS_APPROVE_PLAN	"approve plan '%1'"
#define IDS_CAMERA	"camera"
#define IDS_CATEGORY_EMPTY	"Empty"
#define IDS_CATEGORY_HEADING_PREFIX	"Category"
#define IDS_CATEGORY_NONEMPTY	"Populated"
#define IDS_COPY_PLAN	"copy plan '%1'"
#define IDS_CREATE_CATEGORY	"create category"
#define IDS_CREATE_NEW_PLAN	"create new plan"
#define IDS_CREATE_NEW_STEP	"create new step"
#define IDS_CUSTOMISE_INSTANCE	"customise the selected instance"
#define IDS_CUSTOMISE_STEP	"customise step"
#define IDS_DECISION_STEP_DIALOG_TITLE_PREFIX	"Decision"
#define IDS_DELETE_CATEGORY	"delete category '%1'"
#define IDS_DELETE_MULTIPLE_PLANS	"delete the selected plans"
#define IDS_DELETE_MULTIPLE_STEPS	"delete these steps"
#define IDS_DELETE_PLAN	"delete plan '%1'"
#define IDS_DELETE_SINGLE_CATEGORY	"delete category"
#define IDS_DELETE_SINGLE_PLAN	"delete the selected plan"
#define IDS_DELETE_SINGLE_STEP	"delete this step"
#define IDS_DETERMINE_DATA_POINT_STATE	"determine data point state"
#define IDS_DETERMINE_DATA_POINT_TYPE	"determine data point type"
#define IDS_DETERMINE_IF_NODE_IS_ACCESSIBLE	"determine if node is accessible"
#define IDS_DETERMINE_OWNER_OF_INSTANCE	"determine the owner of the selected instance"
#define IDS_DISPLAY_CATEGORY	"display category"
#define IDS_DISPLAY_TREE_CONTENTS	"display contents of the plan tree"
#define IDS_DP_DATA_TYPE_BOOL	"Boolean"
#define IDS_DP_DATA_TYPE_COMBINED_OUT	"Combined Output"
#define IDS_DP_DATA_TYPE_DERIVED_IN	"Derived Input"
#define IDS_DP_DATA_TYPE_IEEE32	"IEEE single-precision decimal"
#define IDS_DP_DATA_TYPE_INT16_2C	"16-bit signed integer (2's complement)"
#define IDS_DP_DATA_TYPE_INT16_SM	"16-bit signed integer (sign-magnitude)"
#define IDS_DP_DATA_TYPE_INT32_2C	"32-bit signed integer (2's complement)"
#define IDS_DP_DATA_TYPE_INT32_SM	"32-bit signed integer (sign-magnitude)"
#define IDS_DP_DATA_TYPE_TEXT	"Text"
#define IDS_DP_DATA_TYPE_UINT16	"16-bit unsigned integer"
#define IDS_DP_DATA_TYPE_UINT32	"32-bit unsigned integer"
#define IDS_DP_DATA_TYPE_UNDEFINED	"Undefined data type"
#define IDS_DP_TEST_TYPE_EQUAL	"Equal"
#define IDS_DP_TEST_TYPE_GREATER	"Greater Than"
#define IDS_DP_TEST_TYPE_GREATER_OR_EQUAL	"Greater Than or Equal"
#define IDS_DP_TEST_TYPE_LESS	"Less Than"
#define IDS_DP_TEST_TYPE_LESS_OR_EQUAL	"Less Than or Equal"
#define IDS_DP_TEST_TYPE_NOT_EQUAL	"Not Equal"
#define IDS_DP_TEST_TYPE_UNDEFINED	"Undefined test type"
#define IDS_EDIT	"edit"
#define IDS_EDIT_PLAN_STEP	"edit plan step"
#define IDS_ENFORCE_RESTRICTION_ON_CATEGORY	"enforce plan tree access restrictions on the category"
#define IDS_ESTABLISH_LOCALITY_OF_INSTANCE	"establish the locality of the selected instance"
#define IDS_EXPAND_CATEGORY	"expand category"
#define IDS_FAILURE_CATEGORY_ALL_STEPS	"All Step failures"
#define IDS_FAILURE_CATEGORY_DATAPOINT_STEPS	"BRC Step failures only"
#define IDS_FAILURE_CATEGORY_UNDEFINED	"Undefined failure category"
#define IDS_FAILURE_SUMMARY_STEP_DIALOG_TITLE_PREFIX	"Failed Step Summary"
#define IDS_FALSE	"False"
#define IDS_FIND_TREE_NODE	"locate node %1 in the plan tree"
#define IDS_FLOWCHART_EXTENSION	".html"
#define IDS_GROUP	"group"
#define IDS_GROUPS	"groups"
#define IDS_INITIALISE	"initialise"
#define IDS_INVALID	"invalid"
#define IDS_LAUNCH_GUI_APP_STEP_DIALOG_TITLE_PREFIX	"Launch GUI Application"
#define IDS_LAUNCH_PLAN_CONTROLLER	"launch Plan Controller"
#define IDS_LAUNCH_PLAN_EDITOR	"launch Plan Editor"
#define IDS_LAUNCH_SCHEDULING_MANAGER	"launch Scheduling Manager"
#define IDS_LAUNCH_SCHEMATIC_STEP_DIALOG_TITLE_PREFIX	"Launch Schematic"
#define IDS_LOAD_APPLICATIONS	"load the list of applications"
#define IDS_LOAD_CAMERAS	"load the list of cameras"
#define IDS_LOAD_SCHEMATICS	"load the list of SCADA displays"
#define IDS_LOGENTRY_STEP_DIALOG_TITLE_PREFIX	"Log"
#define IDS_MONITOR	"monitor"
#define IDS_MONITORS	"monitors"
#define IDS_MOVE_PLAN	"move plan '%1'"
#define IDS_MSGBOX_CAPTION_ERROR	"Error"
#define IDS_MSGBOX_CAPTION_FATALERROR	"Fatal Error"
#define IDS_MSGBOX_CAPTION_INFORMATION	"Information"
#define IDS_MSGBOX_CAPTION_WARNING	"Warning"
#define IDS_NEW_ACTIVE_PLAN_INSTANCE	"None"
#define IDS_NO	"No"
#define IDS_NODE_LIST_NAME_COLUMN	"Name"
#define IDS_NODE_LIST_STATUS_COLUMN	"Status"
#define IDS_NODE_LIST_TYPE_COLUMN	"Type"
#define IDS_NODE_TYPE_CATEGORY	"Category"
#define IDS_NODE_TYPE_PLAN	"Plan"
#define IDS_NODE_TYPE_ROOT	"Root"
#define IDS_PASTE_STEP	"paste step"
#define IDS_PAUSE_INSTANCE	"pause the selected instance"
#define IDS_PLAN_ABORTED_EXEC_STATE	"Aborted"
#define IDS_PLAN_APPROVED_STATUS	"Approved"
#define IDS_PLAN_COMPLETED_EXEC_STATE	"Completed"
#define IDS_PLAN_EDITOR	"Plan Editor"
#define IDS_PLAN_FAILED_EXEC_STATE	"Failed"
#define IDS_PLAN_GENERAL_DETAIL_TAB_LABEL	"General"
#define IDS_PLAN_HEADING_PREFIX	"Plan"
#define IDS_PLAN_PAUSED_EXEC_STATE	"Paused"
#define IDS_PLAN_PENDING_EXEC_STATE	"Pending"
#define IDS_PLAN_RUNNING_EXEC_STATE	"Running"
#define IDS_PLAN_STEP_DETAIL_TAB_LABEL	"Steps"
#define IDS_PLAN_STOPPED_EXEC_STATE	"Stopped"
#define IDS_PLAN_UNAPPROVED_STATUS	"Unapproved"
#define IDS_PLAN_UNDEFINED_APPROVAL_STATUS	"Undefined"
#define IDS_PLAN_UNDEFINED_EXEC_STATE	"Undefined"
#define IDS_PRESET	"preset"
#define IDS_PROCESS_APPROVAL_STATE_UPDATE	"process approval state update"
#define IDS_PROMPT_STEP_DIALOG_TITLE_PREFIX	"Prompt"
#define IDS_RECIPIENT	"recipient"
#define IDS_REFRESH_CONTENTS	"refresh contents"
#define IDS_RELEASE_CONTROL_OF_INSTANCE	"release control of the selected instance"
#define IDS_RELEASE_LOCK	"release lock"
#define IDS_RENAME	"rename"
#define IDS_REPORT_COMPLETION_STATUS	"report completion status"
#define IDS_RESUME_INSTANCE	"resume the selected instance"
#define IDS_RETRIEVE_APPLICATION_NAME	"retrieve application name"
#define IDS_RETRIEVE_GROUP_LIST	"retrieve group list"
#define IDS_RETRIEVE_MONITORS	"retrieve available monitors"
#define IDS_RETRIEVE_PARAMETER_VALUE	"retrieve parameter value"
#define IDS_RETRIEVE_PLAN	"retrieve plan"
#define IDS_RETRIEVE_WALLBOARD_DETAILS	"retrieve wallboard details"
#define IDS_RETRIEVE_WALLBOARD_LAYOUT_DETAILS	"retrieve wallboard layout details"
#define IDS_RIGHTS_AGENT	"Rights Agent"
#define IDS_RUN_PLAN_STEP_DIALOG_TITLE_PREFIX	"Run Plan"
#define IDS_SAVE_PLAN	"save plan"
#define IDS_SAVE_USER_SETTINGS	"save user settings"
#define IDS_SCHEDULING_AGENT	"Scheduling Agent"
#define IDS_SCHEDULING_MANAGER	"Scheduling Manager"
#define IDS_SEARCH_CATEGORY_PATH	"search category path"
#define IDS_SHOW_EXECUTION_STATUS_FOR_INSTANCE	"show execution status for selected instance"
#define IDS_SMS_AGENT	"SMS Agent"
#define IDS_START_NEW_INSTANCE	"start a new instance"
#define IDS_STEP_BACKGROUND_DECISION_STEP	"User Define Message"
#define IDS_STEP_BACKGROUND_LAUNCH_GUI_APP_STEP	"Launch GUI Application(Auto)"
#define IDS_STEP_BACKGROUND_LAUNCH_SCHEMATIC_STEP	"Launch Schematic(Auto)"
#define IDS_STEP_BACKGROUND_LOG_STEP	"Log(Auto)"
#define IDS_STEP_BACKGROUND_PROMPT_STEP	"Prompt(Auto)"
#define IDS_STEP_HEADING_PREFIX	"Step"
#define IDS_STEP_LIST_DELAY_COLUMN	"Delay\n(mm:ss)"
#define IDS_STEP_LIST_DESCRIPTION_COLUMN	"Description"
#define IDS_STEP_LIST_IGNORE_FAILURE_COLUMN	"Ignore failure"
#define IDS_STEP_LIST_NAME_COLUMN	"Name"
#define IDS_STEP_LIST_NOWAIT_COLUMN	"No Wait"
#define IDS_STEP_LIST_SKIP_COLUMN	"Skip"
#define IDS_STEP_LIST_STEP_COLUMN	"Step"
#define IDS_STEP_LIST_TYPE_COLUMN	"Type"
#define IDS_STEP_PARAMETER_ABORT_STEP	"Abort Step"
#define IDS_STEP_PARAMETER_ACTION_TYPE	"Operate Type"
#define IDS_STEP_PARAMETER_APPLICATION	"Application"
#define IDS_STEP_PARAMETER_CAMERA_MODE	"Camera Mode"
#define IDS_STEP_PARAMETER_CAMERA_NAME	"Camera Name"
#define IDS_STEP_PARAMETER_CAMERA_PRESET	"Camera Preset"
#define IDS_STEP_PARAMETER_CANCEL_STEP	"Cancel Step"
#define IDS_STEP_PARAMETER_COMMAND_LINE	"Command Line"
#define IDS_STEP_PARAMETER_DATA_POINT_NAME	"Data Point Name"
#define IDS_STEP_PARAMETER_DATA_POINT_NEW_VALUE	"Data Point New Value"
#define IDS_STEP_PARAMETER_DATA_POINT_TEST_TYPE	"Data Point Test Type"
#define IDS_STEP_PARAMETER_DATA_POINT_TEST_VALUE	"Data Point Test Value"
#define IDS_STEP_PARAMETER_DECISION_MESSAGE	"Decision Message"
#define IDS_STEP_PARAMETER_EVAL_EXP	"Evaluate Expression Step"
#define IDS_STEP_PARAMETER_EVAL_INSTRUCTIONS	"Constants:   0 1 2 3 4 5 6 7 8 9 . TRUE FALSE ( )\nOperators:   SQRT * / + - ^ < > =  != >= <=\nBoolean operators:   AND OR XOR NOT\n "
#define IDS_STEP_PARAMETER_FAILURE_CATEGORY	"Failure Category"
#define IDS_STEP_PARAMETER_FAILURE_STEP	"Failure Step"
#define IDS_STEP_PARAMETER_HEIGHT	"Height"
#define IDS_STEP_PARAMETER_IGNORE_STEP	"Ignore Step"
#define IDS_STEP_PARAMETER_JUMP_STEP	"Target Step"
#define IDS_STEP_PARAMETER_LAYOUT_NAME	"Layout Name"
#define IDS_STEP_PARAMETER_LIST_NAME_COLUMN	"Parameter Name"
#define IDS_STEP_PARAMETER_LIST_VALUE_COLUMN	"Parameter Value"
#define IDS_STEP_PARAMETER_LOG_MESSAGE	"Log Message"
#define IDS_STEP_PARAMETER_MANDATORY_LOG	"Mandatory Log Entry"
#define IDS_STEP_PARAMETER_MANUAL_PLAN_LAUNCH	"Manual Plan Launch"
#define IDS_STEP_PARAMETER_MESSAGEBOX_STYLE	"Messagebox Style"
#define IDS_STEP_PARAMETER_MONITOR_NAME	"Monitor Name"
#define IDS_STEP_PARAMETER_NO_ENABLED	"No Button Enabled"
#define IDS_STEP_PARAMETER_NO_LABEL	"No Button Label"
#define IDS_STEP_PARAMETER_NO_STEP	"No Step"
#define IDS_STEP_PARAMETER_NOTIFY_PEER	"Notify Peer"
#define IDS_STEP_PARAMETER_OK_STEP	"OK Step"
#define IDS_STEP_PARAMETER_PA_CHIME	"Chime"
#define IDS_STEP_PARAMETER_PA_CYCLIC	"Cyclic"
#define IDS_STEP_PARAMETER_PA_DURATION	"Duration"
#define IDS_STEP_PARAMETER_PA_INTERVAL	"Interval (sec)"
#define IDS_STEP_PARAMETER_PA_MESSAGE	"Message"
#define IDS_STEP_PARAMETER_PA_STATION	"PA Station"
#define IDS_STEP_PARAMETER_PA_TIS_SYNCH	"TIS Synchronised"
#define IDS_STEP_PARAMETER_PA_ZONE	"Zone"
#define IDS_STEP_PARAMETER_PAUSE_ENABLED	"Pause Button Enabled"
#define IDS_STEP_PARAMETER_PAUSE_LABEL	"Pause Button Label"
#define IDS_STEP_PARAMETER_PENDING_STEP	"Pending Step"
#define IDS_STEP_PARAMETER_PLAN_PATH	"Plan Path"
#define IDS_STEP_PARAMETER_POSITION	"X and/or Y Coordinate"
#define IDS_STEP_PARAMETER_PRESET_NAME	"Camera Preset Name"
#define IDS_STEP_PARAMETER_PROFILE	"Operator Profile"
#define IDS_STEP_PARAMETER_PROFILE_NAME	"Profile Name"
#define IDS_STEP_PARAMETER_PROMPT_MESSAGE	"Prompt Message"
#define IDS_STEP_PARAMETER_RECORDING_UNIT_NAME	"Recording Unit Name"
#define IDS_STEP_PARAMETER_RESPONSE_TIMEOUT	"Response Timeout"
#define IDS_STEP_PARAMETER_RETRY_STEP	"Retry Step"
#define IDS_STEP_PARAMETER_SCHEMATIC	"Schematic Name"
#define IDS_STEP_PARAMETER_SCREEN	"Display"
#define IDS_STEP_PARAMETER_SMS_MESSAGE	"SMS Message"
#define IDS_STEP_PARAMETER_SMS_RECIPIENT	"SMS Recipient"
#define IDS_STEP_PARAMETER_STATION	"Station"
#define IDS_STEP_PARAMETER_SUCCESS_STEP	"Success Step"
#define IDS_STEP_PARAMETER_TIME_SPAN	"Timespan"
#define IDS_STEP_PARAMETER_TIS_DURATION	"Duration"
#define IDS_STEP_PARAMETER_TIS_MESSAGE	"Message"
#define IDS_STEP_PARAMETER_TIS_PID_LIST	"PID List"
#define IDS_STEP_PARAMETER_TIS_PRIORITY	"Priority"
#define IDS_STEP_PARAMETER_TIS_SCENE	"TIS Scene"
#define IDS_STEP_PARAMETER_TIS_SIGN	"TIS Sign"
#define IDS_STEP_PARAMETER_TIS_STATION_LEVEL	"Station Level"
#define IDS_STEP_PARAMETER_TRAIN	"Train"
#define IDS_STEP_PARAMETER_TRIGGER_ENTITY	"Trigger Data Point"
#define IDS_STEP_PARAMETER_TRIGGER_ENTITY_CHECK_ACTION	"Trigger Data Point Determination"
#define IDS_STEP_PARAMETER_VMS_NAME	"VMS Name"
#define IDS_STEP_PARAMETER_VMS_SCENE	"VMS Scene"
#define IDS_STEP_PARAMETER_WAIT_FOR_PLAN_COMPLETION	"Wait For Plan Completion"
#define IDS_STEP_PARAMETER_WALLBOARD_NAME	"Wallboard Name"
#define IDS_STEP_PARAMETER_WIDTH	"Width"
#define IDS_STEP_PARAMETER_X_POSITION	"X Coordinate"
#define IDS_STEP_PARAMETER_Y_POSITION	"Y Coordinate"
#define IDS_STEP_PARAMETER_YES_LABEL	"Yes Button Label"
#define IDS_STEP_PARAMETER_YES_STEP	"Yes Step"
#define IDS_STEP_TYPE_ABORT	"Abort"
#define IDS_STEP_TYPE_ACTIVATE_CAMERA_PRESET	"Activate Camera Preset"
#define IDS_STEP_TYPE_ACTIVE_PLAN_CHECK	"Active Plan Check"
#define IDS_STEP_TYPE_ASSIGN_CAMERA_TO_MONITOR	"Assign Camera To Monitor"
#define IDS_STEP_TYPE_CHANGE_MODE	"Change Mode"
#define IDS_STEP_TYPE_DATA_POINT_CHECK	"Data Point Check"
#define IDS_STEP_TYPE_DATA_POINT_SET	"Set Data Point"
#define IDS_STEP_TYPE_DATA_POINT_TIME_CHECK	"Data Point Time Check"
#define IDS_STEP_TYPE_DECISION	"Decision"
#define IDS_STEP_TYPE_END	"End Step"
#define IDS_STEP_TYPE_EVALUATE_EXPRESSION	"Evaluate Expression"
#define IDS_STEP_TYPE_EXECUTE_SCRIPT	"Execute Script"
#define IDS_STEP_TYPE_FAILURE_SUMMARY	"Failure Summary"
#define IDS_STEP_TYPE_JUMP	"Jump"
#define IDS_STEP_TYPE_LAUNCH_GUI_APP	"Launch GUI Application"
#define IDS_STEP_TYPE_LAUNCH_SCHEMATIC	"Launch Schematic"
#define IDS_STEP_TYPE_LOG	"Log"
#define IDS_STEP_TYPE_PAGE	"Page"
#define IDS_STEP_TYPE_PLAN_CHECK_TIMER	"Plan Check Timer"
#define IDS_STEP_TYPE_PLAN_SET_TIMER	"Plan Set Timer"
#define IDS_STEP_TYPE_POPUP_MFT_MESSAGE	"Popup MFT Message"
#define IDS_STEP_TYPE_PROMPT	"Prompt"
#define IDS_STEP_TYPE_RUN_PLAN	"Run Plan"
#define IDS_STEP_TYPE_SEND_SMS_MESSAGE	"Send SMS Message"
#define IDS_STEP_TYPE_SHUTDOWN_SYSTEM	"Shutdown System"
#define IDS_STEP_TYPE_STATION_PUBLIC_ADDRESS	"Station Public Address"
#define IDS_STEP_TYPE_STATION_TRAVELLER_INFO_SYSTEM	"Station Traveller Info System"
#define IDS_STEP_TYPE_TERMINATE_PLAN	"Terminate Plan"
#define IDS_STEP_TYPE_TIS_SET_SCENE	"TIS Set Scene"
#define IDS_STEP_TYPE_TRAIN_PUBLIC_ADDRESS	"Train Public Address"
#define IDS_STEP_TYPE_TRAIN_TRAVELLER_INFO_SYSTEM	"Train Traveller Info System"
#define IDS_STEP_TYPE_UNDEFINED	"Undefined step type"
#define IDS_STEP_TYPE_VIDEO_WALL	"Video Wall"
#define IDS_STEP_TYPE_VMS_BLANKOUT	"VMS Blankout"
#define IDS_STEP_TYPE_VMS_RESTORE_SCHEDULE	"VMS Restore Schedule"
#define IDS_STEP_TYPE_VMS_SET_SCENE	"VMS Set Scene"
#define IDS_STOP_INSTANCE	"stop the selected instance"
#define IDS_TAKE_CONTROL_OF_INSTANCE	"take control of the selected instance"
#define IDS_TIS_LIBRARY_SECTION_EMERGENCY	"Emergency"
#define IDS_TIS_LIBRARY_SECTION_NORMAL	"Normal"
#define IDS_TIS_LIBRARY_SECTION_UNDEFINED	"Undefined"
#define IDS_TIS_MESSAGE_TYPE_STATION	"Station"
#define IDS_TIS_MESSAGE_TYPE_TRAIN	"Train"
#define IDS_TIS_MESSAGE_TYPE_UNDEFINED	"Undefined"
#define IDS_TISMSG_LIST_ID_COLUMN	"ID"
#define IDS_TISMSG_LIST_MESSAGE_COLUMN	"Message"
#define IDS_TISMSG_LIST_PRIORITY_COLUMN	"Priority"
#define IDS_TISMSG_LIST_TYPE_COLUMN	"Type"
#define IDS_TRAIN_GROUP_ALL	"All trains"
#define IDS_TRAIN_GROUP_INBOUND	"Inbound trains"
#define IDS_TRAIN_GROUP_OUTBOUND	"Outbound trains"
#define IDS_TRAIN_GROUP_UNDEFINED	"Undefined train group"
#define IDS_TREE_ALLPLANS_ROOT_LABEL	"All Plans"
#define IDS_TREE_APPROVEDPLANS_ROOT_LABEL	"Approved Plans"
#define IDS_TREE_UNAPPROVEDPLANS_ROOT_LABEL	"Unapproved Plans"
#define IDS_TRUE	"True"
#define IDS_UNAPPROVE_PLAN	"unapprove plan '%1'"
#define IDS_UNDEFINED_TIS_MESSAGE_LIBRARY	"Undefined"
#define IDS_UNKNOWN	"unknown"
#define IDS_UNSPECIFIED	"unspecified"
#define IDS_UPDATE_PLAN_STEP_LIST	"update plan step list"
#define IDS_UPDATE_STATE_PARAMETER_LIST	"update state parameter list"
#define IDS_VIDEO_SWITCH_AGENT	"Video Switch Agent"
#define IDS_VIDEO_WALL_LAYOUT_AGENT	"Video Wall Layout Agent"
#define IDS_VIEW_PLAN_STEP	"view plan step"
#define IDS_VMS	"VMS"
#define IDS_VMS_AGENT	"VMS Agent"
#define IDS_VMS_SCENE	"VMS scene"
#define IDS_VMS_SCENES	"VMS scenens"
#define IDS_VMS_SIGN	"VMS sign"
#define IDS_WALLBOARD	"wallboard"
#define IDS_WALLBOARD_LAYOUT	"wallboard layout"
#define IDS_WALLBOARDS	"wallboards"
#define IDS_YES	"Yes"


typedef enum
{
	ID_DELETE_PLAN = 0,
	ID_DELETE_CATEGORY,

};



#endif