using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    public class ArithmeticSubtractTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+sq8dA", "/6F/Fg")]
        public void TestArithmeticSubtractConstructor01()
        {
            ArithmeticSubtract arithmeticSubtract = new ArithmeticSubtract();
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((OperatorPriority)arithmeticSubtract.Priority);
            recorder.FinishRecording();
            #endregion
        }

    }
}
