using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    public class ArithmeticMultiplyTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/d6/cw", "/kucLg")]
        public void TestArithmeticMultiplyConstructor01()
        {
            ArithmeticMultiply arithmeticMultiply = new ArithmeticMultiply();
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((OperatorPriority)arithmeticMultiply.Priority);
            recorder.FinishRecording();
            #endregion
        }

    }
}
