using Dottest.Framework;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using OPCTrendLib;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    class Base64DecoderTest
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestGetDecoded01()
        {
            Base64Decoder baseDecoder = new Base64Decoder("testing=1".ToCharArray());
            byte[] decodedbyte =  baseDecoder.GetDecoded();
        }


    }
}
