using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;
//using STEE.ISCS.Log.DotTest.Factories;
using System;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    public class ConstantTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+fx+ZA", "+1VfGg")]
        public void TestConstantConstructor01()
        {
            //object value1 = LogLevelFactory.CreateLogLevel01();
            Constant constant = new Constant("CONS");
        }

    }
}
