using Dottest.Framework;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using OPCTrendLib;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    class ConvertHelperTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestChangeType01()
        {          
            //Test Procedure Call
            double i = (double)ConvertHelper.ChangeType(1, typeof(double));  
            //Post Condition Check      
            Assert.AreEqual(i, 1);            
        }

        [ExpectedException(typeof(System.ArgumentNullException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ChangeType01()
        {
            //Test Procedure Call
            object result = ConvertHelper.ChangeType(1, null);
            //Post Condition Check      
            Assert.IsNull(result);
        }

        [ExpectedException(typeof(System.InvalidCastException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ChangeType02()
        {
            //Test Procedure Call
            object result = ConvertHelper.ChangeType(null, typeof(int));
            //Post Condition Check      
            Assert.IsNull(result);
        }
                      
        [ExpectedException(typeof(System.InvalidCastException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ChangeType03()
        {
            //Test Procedure Call
            object result = ConvertHelper.ChangeType("true", typeof(int));
            //Post Condition Check      
            Assert.IsNull(result);
        }

        [ExpectedException(typeof(System.InvalidCastException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ChangeType04()
        {
            Evaluator eval = new Evaluator();
            //Test Procedure Call
            object result = ConvertHelper.ChangeType(eval, typeof(int));
            //Post Condition Check      
            Assert.IsNull(result);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ChangeType05()
        {
            //Test Procedure Call
            object result = ConvertHelper.ChangeType(null, typeof(int));
            //Post Condition Check      
            Assert.IsNull(result);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestToString01()
        {
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(1);
            //Post Condition Check      
            Assert.AreEqual("1", result);
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ToString01()
        {
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(null);
            //Post Condition Check      
            Assert.AreEqual(string.Empty, result);
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ToString02()
        {           
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(DBNull.Value);
            //Post Condition Check      
            Assert.AreEqual(string.Empty, result);
        }

        [ExpectedException(typeof(System.InvalidCastException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ToString03()
        {
            Evaluator eval = new Evaluator();
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(eval);
            //Post Condition Check      
            Assert.AreEqual(string.Empty, result);
        }

        [ExpectedException(typeof(System.InvalidCastException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ToString04()
        {
            Evaluator eval = new Evaluator();
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(eval);
            //Post Condition Check      
            //Assert.AreEqual(string.Empty, result);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestErr_ToString05()
        {
            Evaluator eval = new Evaluator();
            //Test Procedure Call
            string result = (string)ConvertHelper.ToString(eval);
            //Post Condition Check      
            //Assert.AreEqual(string.Empty, result);
        }

    }
}
