using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;
using System;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    public class ScannerExceptionTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/dyA9w", "/BgAuA")]
        public void TestScannerExceptionConstructor01()
        {
            Error errorCode = Error.VariableNotExist;
            ScannerException scannerException = new ScannerException(errorCode);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((string)scannerException.HelpLink);
            recorder.Record((string)scannerException.Message);
            recorder.Record((string)scannerException.Source);
            recorder.Record((string)scannerException.StackTrace);
            recorder.FinishRecording();
            #endregion
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/pSGnQ", "+pP5gg")]
        public void TestScannerExceptionConstructor02()
        {
            Error errorCode = Error.VariableNotExist;
            int pos = 1;
            ScannerException scannerException = new ScannerException(errorCode, pos);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((string)scannerException.HelpLink);
            recorder.Record((string)scannerException.Message);
            recorder.Record((string)scannerException.Source);
            recorder.Record((string)scannerException.StackTrace);
            recorder.FinishRecording();
            #endregion
        }

    }
}
