using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;
using System;

namespace DotTest.OPCTrendLib
{
    [TestFixture()]
    public class TypeNamePartTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+IRSyw", "+HdWWA")]
        public void TestTypeNamePartConstructor01()
        {
            string part = string.Empty;
            TypeNamePart typeNamePart = new TypeNamePart(part);
        }

    }
}
