using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.MulLanguage;

namespace STEE.ISCS.MulLanguage.DotTest
{
    [TestFixture()]
    public class MessageBoxButtonStringTests
    {
        [SetUp]
        public void FixtureSetup()
        {
            StringHelper.ReleaseInstance();
        }

        [TearDown]
        public void FixtureTearDown()
        {
            MessageBoxButtonString.ReleaseInstance();
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+4xN5w", "/ACUzA")]
        public void TestGetInstance01()
        {
            MessageBoxButtonString messageBoxButtonString = MessageBoxButtonString.GetInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+EGX+g", "+XYDTw")]
        public void TestReleaseInstance01()
        {
            MessageBoxButtonString.ReleaseInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+TVByw", "/7IpoA")]
        public void TestMessageBoxButtonStringConstructor01()
        {
            MessageBoxButtonString messageBoxButtonString = MessageBoxButtonString.GetInstance();
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestAddStringHelper01()
        {
            MessageBoxButtonString messageBoxButtonString = MessageBoxButtonString.GetInstance();
            //test Procedure Call
            messageBoxButtonString.AddStringHelper();
            //Post Condition Check

            //duplicate addition of same string id
            Accessor messageBoxStringAccessor = ReflectionAccessor.Wrap(messageBoxButtonString);
            messageBoxStringAccessor.SetField("m_init", false);
            messageBoxButtonString.AddStringHelper();
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestRemoveStringHelper01()
        {
            MessageBoxButtonString messageBoxButtonString = MessageBoxButtonString.GetInstance();
            messageBoxButtonString.AddStringHelper();
            //test Procedure Call
            messageBoxButtonString.RemoveStringHelper();
            //Post Condition Check
        }

    }
}
