using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.MulLanguage;

namespace STEE.ISCS.MulLanguage.DotTest
{
    [TestFixture()]
    public class StringItemTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/Yly+Q", "+hiRxw")]
        public void TestStringItemConstructor01()
        {
            StringItem stringItem = new StringItem();
        }

    }
}
