#ifndef TRANSACTIVEABOUTBOX_GLOBAL_H
#define TRANSACTIVEABOUTBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TRANSACTIVEABOUTBOX_LIB
# define TRANSACTIVEABOUTBOX_EXPORT Q_DECL_EXPORT
#else
# define TRANSACTIVEABOUTBOX_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSACTIVEABOUTBOX_GLOBAL_H
