using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCHeader;

namespace DotTest.Factories.OPCTrendLib.OPCHeader
{
    [TestFixture(), ObjectFactoryType()]
    public class OPCServerListFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+qqqyg", "+dAy7g")]
        public static OPCServerList CreateOPCServerList01()
        {
            OPCServerList oPCServerList = new OPCServerList();
            return oPCServerList;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCServerList01()
        {
            OPCServerList oPCServerList = CreateOPCServerList01();
            Assert.IsNotNull(oPCServerList);
        }

    }
}
