using DAO.Trending;
using Dottest.Framework;
using NUnit.Framework;
using Entity.Trending;
using System.Collections.Generic;

namespace DAO.Trending.DotTest
{
    [TestFixture()]
    public class FormulaerDAOTests
    {
        private FormulaerDAO formulaerDAO;

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            formulaerDAO = new FormulaerDAO();
            TestDBInit.openConn();
        }

//         [TestCaseUnverified("Test case not verified")]
//         [TestCaseAutogenerated]
//         [TestAuthor("user")]
//         [Test]
//         [HashCode("+Xz8Vg", "/UWyJw")]
//         public void TestFormulaerDAOConstructor01()
//         {
//             FormulaerDAO formulaerDAO = new FormulaerDAO();
//         }

        [Test]
        public void TestGetAllformulaGrpNames()
        {
            formulaerDAO.GetAllformulaGrpNames();
        }

        [Test]
        public void Test_Delete_Insert_Get_FormulaList()
        {
            string grpName = "UnitTestFormulaGrp";

            formulaerDAO.DeleteAllFormulaInGrp(grpName);

            List<EtyFormula> formulaList = new List<EtyFormula>();
            EtyFormula formula1 = new EtyFormula();
            formula1.DPLblName = "Lbl1";
            formula1.DPEquation = "equationStr1";

            EtyFormula formula2 = new EtyFormula();
            formula2.DPEquation="equationStr2";
            formula2.DPLblName = "Lbl2";
            formulaList.Add(formula1);
            formulaList.Add(formula2);

            //formulaerDAO.InsertFormulaListToGrp(formulaList, grpName);
            formulaerDAO.SaveFormulaListToGrp(formulaList, grpName);

            formulaerDAO.GetFormulasByCfgName(grpName);
        }

        [Test]
        public void TestSaveFormulaListToGrp02()
        {
            //test rollback 
            formulaerDAO.SaveFormulaListToGrp(null, "");
        }

        [Test]
        public void TestGetAllformulaGrpNames_GetFormulasByCfgName02()
        {
            //exception
            formulaerDAO.GetAllformulaGrpNames();
            formulaerDAO.GetFormulasByCfgName("UnitTestFormulaGrp");
        }
    }
}
