using DAO.Trending;
using Dottest.Framework;
using NUnit.Framework;
using Entity.Trending;
using Entity.Trending;
using System.Collections.Generic;
using System.Drawing;

namespace DAO.Trending.DotTest
{
    [TestFixture()]
    public class HistDataPointDAOTests
    {
        private HistDataPointDAO histDataPointDAO;

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            histDataPointDAO = new HistDataPointDAO();
            TestDBInit.openConn();
        }

//         [TestCaseUnverified("Test case not verified")]
//         [TestCaseAutogenerated]
//         [TestAuthor("user")]
//         [Test]
//         [HashCode("/DmPrA", "+Q8u8g")]
//         public void TestHistDataPointDAOConstructor01()
//         {
//             HistDataPointDAO histDataPointDAO = new HistDataPointDAO();
//         }

        [Test]
        public void TestGetAllHistDPGrpNames()
        {
            histDataPointDAO.GetAllHistDPGrpNames();
        }

        [Test]
        public void Test_Delete_Insert_GetHistDPGrp()
        {
            string histDPGrpName = "unitTest_histDPGrp";

            histDataPointDAO.DeleteAllHistDPInGrp(histDPGrpName);

            List<EtyHistDataPoint> histDPList=new List<EtyHistDataPoint>();
            EtyHistDataPoint dp1= new EtyHistDataPoint();
            EtyHistDataPoint dp2= new EtyHistDataPoint();
            dp1.DPName = "histDP1";
            dp2.DPName = "histDP2";
            dp1.EntityKey = 1;
            dp2.DPColor = Color.Red.ToArgb().ToString();
            dp2.DPLblName = "lbl1";
            dp2.DPServer = TestDBInit.OPCSERVER_NAME;
            dp2.DPHost = TestDBInit.HOST_NAME;
            histDPList.Add(dp1);
            histDPList.Add(dp2);

           // histDataPointDAO.InsertHistDPListToGrp(histDPList, histDPGrpName);
            histDataPointDAO.SaveHistDPListToGrp(histDPList, histDPGrpName);

            histDataPointDAO.GetHistDPByCfgName(histDPGrpName);
        }

        [Test]
        public void TestSave02()
        {
            //test rollback
            histDataPointDAO.SaveHistDPListToGrp(null, "");
        }
        [Test]
        public void TestExceptions()
        {
            histDataPointDAO.GetAllHistDPGrpNames();
            histDataPointDAO.GetHistDPByCfgName("unitTest_histDPGrp");
        }

        [Test]
        public void TestInsertHistDPListToGrp02()
        {
            //test "executeOK == false"

            List<EtyHistDataPoint> histDPList = new List<EtyHistDataPoint>();
            EtyHistDataPoint dp1 = new EtyHistDataPoint();
            dp1.DPName = "histDP1";
            dp1.EntityKey = 1;
            histDPList.Add(dp1);


            histDataPointDAO.InsertHistDPListToGrp(histDPList, "");
        }
    }
}
