using DAO.Trending;
using Dottest.Framework;
using NUnit.Framework;
using DAO.Trending.Common;

namespace DAO.Trending.DotTest
{
    [TestFixture()]
    public class SimpleDatabaseTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+ZQ7IA", "+jif/w")]
        public void TestGetInstance01()
        {
            SimpleDatabase simpleDatabase = SimpleDatabase.GetInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+1sGow", "++2LdA")]
        public void TestSimpleDatabaseConstructor01()
        {
            SimpleDatabase simpleDatabase = SimpleDatabase.GetInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+fLFKg", "+jNgpg")]
        public void TestReleaseInstance01()
        {
            SimpleDatabase.ReleaseInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+ZQ7IA", "+jif/w")]
        public void TestGetInstance02()
        {
            SimpleDatabase simpleDatabase = SimpleDatabase.GetInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+1sGow", "++2LdA")]
        public void TestSimpleDatabaseConstructor02()
        {
            SimpleDatabase simpleDatabase = SimpleDatabase.GetInstance();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+fLFKg", "+jNgpg")]
        public void TestReleaseInstance02()
        {
            SimpleDatabase.ReleaseInstance();
        }

    }
}
