using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCDataInterface;

namespace DotTest.OPCTrendLib.OPCDataInterface
{
    [TestFixture()]
    public class OPCITEMDEFinternTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+5FH7Q", "+uyWZA")]
        public void TestOPCITEMDEFinternConstructor01()
        {
            OPCITEMDEFintern oPCITEMDEFintern = new OPCITEMDEFintern();
        }

    }
}
