using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.MVC;

namespace STEE.ISCS.MVC.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class ViewManagerFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+CKeoQ", "/cDk7w")]
        public static ViewManager CreateViewManager01()
        {
            ViewManager viewManager = ViewManager.GetInstance();
            return viewManager;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateViewManager01()
        {
            ViewManager viewManager = CreateViewManager01();
            Assert.IsNotNull(viewManager);
        }

    }
}
