using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCData;

namespace DotTest.Factories.OPCTrendLib.OPCData
{
    [TestFixture(), ObjectFactoryType()]
    public class OPCItemStateFactory
    {
        [ObjectFactoryMethod]
        [HashCode("//0oBQ", "/6yITA")]
        public static OPCItemState CreateOPCItemState01()
        {
            OPCItemState oPCItemState = new OPCItemState();
            return oPCItemState;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCItemState01()
        {
            OPCItemState oPCItemState = CreateOPCItemState01();
            Assert.IsNotNull(oPCItemState);
        }

    }
}
