using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCData;

namespace DotTest.Factories.OPCTrendLib.OPCData
{
    [TestFixture(), ObjectFactoryType()]
    public class OPCItemResultFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+qVYSQ", "+qg7lA")]
        public static OPCItemResult CreateOPCItemResult01()
        {
            OPCItemResult oPCItemResult = new OPCItemResult();
            return oPCItemResult;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCItemResult01()
        {
            OPCItemResult oPCItemResult = CreateOPCItemResult01();
            Assert.IsNotNull(oPCItemResult);
        }

    }
}
