using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCData;

namespace DotTest.Factories.OPCTrendLib.OPCData
{
    [TestFixture(), ObjectFactoryType()]
    public class ReadCompleteEventArgsFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+ab6Ig", "+uZkOQ")]
        public static ReadCompleteEventArgs CreateReadCompleteEventArgs01()
        {
            ReadCompleteEventArgs readCompleteEventArgs = new ReadCompleteEventArgs();
            return readCompleteEventArgs;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateReadCompleteEventArgs01()
        {
            ReadCompleteEventArgs readCompleteEventArgs = CreateReadCompleteEventArgs01();
            Assert.IsNotNull(readCompleteEventArgs);
        }

    }
}
