using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCData;

namespace DotTest.Factories.OPCTrendLib.OPCData
{
    [TestFixture(), ObjectFactoryType()]
    public class WriteCompleteEventArgsFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+d/mjQ", "/hlb5w")]
        public static WriteCompleteEventArgs CreateWriteCompleteEventArgs01()
        {
            WriteCompleteEventArgs writeCompleteEventArgs = new WriteCompleteEventArgs();
            return writeCompleteEventArgs;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateWriteCompleteEventArgs01()
        {
            WriteCompleteEventArgs writeCompleteEventArgs = CreateWriteCompleteEventArgs01();
            Assert.IsNotNull(writeCompleteEventArgs);
        }

    }
}
