using DAO.Trending;
using Dottest.Framework;
using NUnit.Framework;

namespace DAO.Trending.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class FormulaerDAOFactory
    {
        [ObjectFactoryMethod]
        [HashCode("/0cGHA", "+v1LJg")]
        public static FormulaerDAO CreateFormulaerDAO01()
        {
            FormulaerDAO formulaerDAO = new FormulaerDAO();
            return formulaerDAO;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateFormulaerDAO01()
        {
            FormulaerDAO formulaerDAO = CreateFormulaerDAO01();
            Assert.IsNotNull(formulaerDAO);
        }

    }
}
