using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.OPCProxy;
using System;

namespace STEE.ISCS.OPCProxy.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class OPCDataItemFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+JKfOQ", "/iSZNQ")]
        public static OPCDataItem CreateOPCDataItem01()
        {
            string opcID = string.Empty;
            int handleClient = int.MinValue;
            OPCDataItem oPCDataItem = new OPCDataItem(opcID, handleClient);
            return oPCDataItem;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCDataItem01()
        {
            OPCDataItem oPCDataItem = CreateOPCDataItem01();
            Assert.IsNotNull(oPCDataItem);
        }

        [ObjectFactoryMethod]
        [HashCode("+JKfOQ", "/cKt+w")]
        public static OPCDataItem CreateOPCDataItem02()
        {
            string opcID = string.Empty;
            int handleClient = int.MaxValue;
            OPCDataItem oPCDataItem = new OPCDataItem(opcID, handleClient);
            return oPCDataItem;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCDataItem02()
        {
            OPCDataItem oPCDataItem = CreateOPCDataItem02();
            Assert.IsNotNull(oPCDataItem);
        }

        [ObjectFactoryMethod]
        [HashCode("+JKfOQ", "+I4dyQ")]
        public static OPCDataItem CreateOPCDataItem03()
        {
            string opcID = string.Empty;
            int handleClient = 0;
            OPCDataItem oPCDataItem = new OPCDataItem(opcID, handleClient);
            return oPCDataItem;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateOPCDataItem03()
        {
            OPCDataItem oPCDataItem = CreateOPCDataItem03();
            Assert.IsNotNull(oPCDataItem);
        }

    }
}
