//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EventViewer.rc
//
#define ID_APPLY                        3
#define ID_DEFAULT_FILTER               4
#define IDM_ABOUTBOX                    0x0010
#define IDS_SUBSYSTEM_MULTI_DIALOG      17
#define IDS_LOC_MULTI_DIALOG            18
#define IDS_OPT_MULTI_DIALOG            19
#define IDS_SYSTEM_MULTI_DIALOG         20
#define IDS_ALARM_TYPE_DIALOG           21
#define IDS_ALARM_STATE_DIALOG          22
#define IDS_OPERATION_STR               23
#define IDS_PRINT_HEADER_STRING         23
#define IDS_MAINTENCE_STR               24
#define IDS_EXPORT_MSG1_STR             24
#define IDS_BOTH_STR                    25
#define IDS_EVENT_COUNT_STR             26
#define IDS_SAVE_MSG1                   27
#define IDS_APP_NAME_STRING             27
#define IDS_PRINT_STRING                28
#define IDS_EXPORT_STR                  29
#define IDS_FILTER_STR                  30
#define IDS_PREVIOUS_STR                31
#define IDS_NEXT_STR                    32
#define IDS_INCIDENT_REPORT_STR         33
#define IDS_ALARM_MANAGER_STR           34
#define IDS_SLASH_FILTER_ON_STR         35
#define IDS_ERROR_LOAD_STR              36
#define IDS_ERROR_LOADED_STR            37
#define IDS_ERROR_SAVE_STR              38
#define IDS_ERROR_SAVED_STR             39
#define IDS_ERROR_DELETE_STR            40
#define IDS_ERROR_DELETED_STR           41
#define IDS_NAMED_FILTER_LABEL_STR      42
#define IDS_EVENT_ONLY_STR              43
#define IDS_ALARM_FILTER_MESSAGE        44
#define IDS_NAMEDFILTER_AVALANCHE       46
#define IDS_FILTER_APPLICATION_SUBSYSTEM 47
#define IDS_FILTER_PHYSICAL_SUBSYSTEM   48
#define IDS_FILTER_SYSTEM_STR           49
#define IDS_FILTER_SUBSYSTEM_STR        50
#define IDS_FILTER_LOCATION             51
#define IDS_FILTER_OPERATOR             52
#define IDS_FILTER_OPERATOR_STR         53
#define IDS_FILTER_LOCATION_STR         54
#define IDS_FILTER_EVENTTYPE            55
#define IDS_FILTER_ISCS_SYSTEM          56
#define IDS_FILTER_TMTYPE               57
#define IDS_FILTER_ALARMSTATE           58
#define IDS_FILTER_ASSET                59
#define IDS_FILTER_DESCRIPTION          60
#define IDS_FILTER_SEVERITY             61
#define IDS_FILTER_ALARMTYPE            62
#define IDS_FILTER_ALARMID              63
#define IDS_NAMEDFILTER_DEFAULT         64
#define IDS_HIDDEN_COLUMN_ALARMID       65
#define IDS_HIDDEN_COLUMN_ACKED         66
#define IDS_HIDDEN_COLUMN_STATUS        67
#define IDS_FONT_NAME_STR               68
#define IDS_STATUS_ATS_QUERYING_STR     69
#define IDS_STATUS_ISCS_QUERYING        70
#define IDS_STATUS_ATS_READY            71
#define IDS_STATUS_ISCS_READY           72
#define IDS_STATUS_ATS_UNHEALTHY        73
#define IDS_STATUS_ISCS_UNHEALTHY       74
#define IDS_STATUS_ATS_DISABLED         75
#define IDS_STATUS_ICSC_DISABLED        76
#define IDS_USER_DEFINED_NAMED_FILTER_STR 77
#define IDD_EVENTVIEWER_DIALOG          102
#define IDC_PROGRESS                    102
#define IDC_PRINT                       106
#define IDC_EXPORT                      107
#define IDC_PREVIOUS                    108
#define IDC_NEXT                        109
#define IDC_VIEW_INCIDENTS              110
#define IDC_ALARM_MANAGER               111
#define ID_INDICATOR_CAP                112
#define IDS_COLUMN_DATETIME_STRING      117
#define IDS_COLUMN__SEVERITY_STRING     118
#define IDS_COLUMN_ASSET_STRING         119
#define IDS_COLUMN_ALARM_STATUS_STRING  120
#define IDS_COLUMN_DESCRIPTION_STRING   121
#define IDS_COLUMN_VALUE_STRING         122
#define IDS_COLUMN_T_STRING             123
#define IDS_COLUMN_MMS_STRING           124
#define IDS_COLUMN_DSS_STRING           125
#define IDS_COLUMN_AVL_STRING           126
#define IDS_COLUMN_OPERATOR_STRING      127
#define IDR_MAINFRAME                   128
#define IDR_EV_MAIN_MENU                129
#define IDI_REFRESH                     130
#define IDS_COLUMN_COMMENT_STRING       131
#define IDI_REFRESH_HOT                 133
#define IDI_PRINT_HOT                   136
#define IDI_PRINT                       137
#define IDI_SAVE_HOT                    138
#define IDI_SAVE                        139
#define IDI_FILTERS                     140
#define IDI_FILTERS_HOT                 141
#define IDI_NEXT                        142
#define IDI_PREVIOUS_HOT                143
#define IDI_PREVIOUS                    145
#define IDI_NEXT_HOT                    146
#define IDI_UPDATING                    147
#define IDI_UPDATING_HOT                148
#define ID_NAMED_FILTER_COMBO           149
#define ID_EVENT_LEVEL_COMBO            150
#define IDI_INCIDENT_HOT                151
#define IDI_INCIDENT                    152
#define IDD_MULTIPLE_LOAD               155
#define IDD_WAIT_FOR_CLOSE              158
#define IDB_CAP_ACTIVE                  160
#define IDI_CAP_ACTIVE                  161
#define IDD_COMBINED_EVENT_FILTER       163
#define IDI_PAGE_UP                     164
#define IDI_PAGE_DOWN                   165
#define IDI_ALARMMANAGER_HOT            167
#define IDI_ALARMMANAGER                168
#define IDD_SHOW_COMMENT                169
#define IDD_FILTER_NAME                 170
#define IDS_SAVE_ERR_STRING             172
#define IDS_FILE_ERR_STRING             173
#define IDS_USER_FILTER_NAME            174
#define IDS_DEFAULT_FILTER_NAME         175
#define IDS_DEFINED_FILTER_NAME         176
#define IDC_SUBSYSTEM                   1000
#define IDC_PAGER_CTRL                  1001
#define IDC_EVENTS_TBAR                 1002
#define IDC_EVENT_LIST                  1002
#define IDC_SUBSYSTEM_EXT               1003
#define IDC_LOCATION                    1004
#define IDC_LOCATION_EX                 1005
#define IDC_FROM_DATE                   1006
#define IDC_FROM_TIME                   1007
#define IDC_TO_DATE                     1008
#define IDC_TO_TIME                     1009
#define IDC_LOAD_LIST                   1010
#define IDC_OPERATOR_EXT                1010
#define IDC_MENU_LINE                   1011
#define IDC_EVENTTYPE_EXT               1011
#define IDC_ASSET                       1012
#define IDC_ALARM_ID                    1013
#define IDC_DESCRIPTION                 1014
#define IDC_STATUS                      1014
#define IDC_ALARMTYPE_EXT               1015
#define IDC_ALARMTYPE_EXT2              1016
#define IDC_SAVE                        1017
#define IDC_PAGE_UP                     1018
#define IDC_BUTTON_SAVEFILTER           1018
#define IDC_PAGE_DOWN                   1019
#define IDC_BUTTON_DELETEFILTER         1019
#define IDC_LIST_PLACEHOLDER            1020
#define IDC_FROM                        1021
#define IDC_EDIT_ALARM_COMMENT          1022
#define IDC_EVENT                       1023
#define IDC_COMBO_NAMEDFILTER           1023
#define IDC_EDIT_FILTER_NAME            1024
#define IDC_STATIC_SEVERITY             1025
#define IDC_STATIC_SEVERITY2            1026
#define IDC_OPERATION_GRP_STATIC        1026
#define IDC_RADIO1                      1027
#define IDC_OPT_RADIO1                  1027
#define IDC_SYSTEM_GRP_STATIC           1028
#define IDC_RADIO2                      1029
#define IDC_MAINT_RADIO2                1029
#define IDC_RADIO3                      1030
#define IDC_BOTH_RADIO3                 1030
#define IDC_RADIO4                      1031
#define IDC_ALL_RADIO4                  1031
#define IDC_OPERATOR_GRP_STATIC         1032
#define IDC_EQUIPMENT_STATIC            1033
#define IDC_EQUIPMENT_GRP_STATIC        1033
#define IDC_DESCRIPTION_GRP_STATIC      1034
#define IDC_NAMED_FILTER_STATIC         1035
#define IDC_DATE_TIME_GRP_STATIC        1036
#define IDC_ALARM_STATE_GRP_STATIC      1037
#define IDC_ALARM_ID_GRP_STATIC         1038
#define IDC_ALARM_TYPE_GRP_STATIC       1039
#define IDC_SUBSYSTEM_GRP_STATIC        1040
#define IDC_LOC_GRP_STATIC              1041
#define IDC_CLOSE_DISPLAY_STATIC        1042
#define IDC_OPERATOR                    1054
#define IDC_SEVERITY                    1055
#define IDC_SYSTEM                      1056
#define IDC_ALARM_TYPE                  1057
#define IDC_ALARM_STATE                 1058
#define IDC_CURRENT                     1062
#define ID_FILE_EXIT                    32772
#define IDC_VIEW_FILTERS                32774
#define ID_VIEW_TOOLBARS_STATUSBAR      32777
#define ID_VIEW_TOOLBARS_TOOLBAR        32778
#define IDC_LOAD_AUDIT_FILTER           32789
#define IDC_LOAD_DATAPOINT_FILTER       32790
#define IDC_COLUMNS                     32793
#define IDC_STATUS_BAR                  32794
#define IDC_TOOL_BAR                    32795
#define IDC_SEVERITY_LIST               32797
#define IDC_SHOW_ALL                    32809
#define ID_INDICATOR_SIZE               59142
#define ID_FILE_EXPORT                  59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
