//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ControlStation.rc
//
#include <QtGlobal>
#define IDS_ABOUTBOX                    QT_TR_NOOP("&About Control Station")
#define IDS_REQUESTED_APPLICATION       QT_TR_NOOP("the requested application")
#define IDS_EXIT                        QT_TR_NOOP("exit")
#define IDS_RESTART                     QT_TR_NOOP("restart the workstation")
#define IDS_CHANGE_PROFILE              QT_TR_NOOP("change profile")
#define IDS_CHANGE_OPERATOR             QT_TR_NOOP("change operator")
#define IDS_OPERATOR_OVERRIDE           QT_TR_NOOP("override operator")
#define IDS_CHANGE_PASSWORD             QT_TR_NOOP("change password")
#define IDS_LOGOUT                      QT_TR_NOOP("logout")
#define IDS_LOGIN                       QT_TR_NOOP("login")
#define IDS_ONLINE                      QT_TR_NOOP("online")
#define IDS_OFFLINE                     QT_TR_NOOP("offline")
#define IDS_OPERATOR                    QT_TR_NOOP("operator")
#define IDS_PROFILE                     QT_TR_NOOP("profile")
#define IDS_LOCATION                    QT_TR_NOOP("location")
#define IDS_DISPLAY                     QT_TR_NOOP("display")
#define IDS_APPNAME                     QT_TR_NOOP("Control Station")
#define IDS_BANNER                      QT_TR_NOOP("banner")
#define IDS_REMOVE_OPERATOR_OVERRIDE    QT_TR_NOOP("remove operator override")
#define IDS_TASK_MANAGER                QT_TR_NOOP("task manager")
#define IDS_SHORTCUT_NAME               QT_TR_NOOP("shortcut name")
#define IDS_SUBSYSTEM                   QT_TR_NOOP("subsystem")
#define IDS_AUTHENTICATION_AGENT        QT_TR_NOOP("Authentication Agent")
#define IDS_SUCC                        QT_TR_NOOP("The Screen Saver has been successfully installed!")
#define IDS_FAIL                        QT_TR_NOOP("The installation failed. You may restart your computer and try again.")
#define IDS_SCRFILENAME                 QT_TR_NOOP("TransactScreensaver.scr")
#define IDS_PASSWORD                    QT_TR_NOOP("password")
#define IDS_REQUEST_FORMAT_WITH_LOCATION QT_TR_NOOP("Do you accept the request for the transfer of rights from:\n\t %s/%s")
#define IDS_LOCATION_AND_SUBSYSTEM_FORMAT QT_TR_NOOP("\t%1\n%2\n")
#define IDS_SUBSYSTEM_FORMAT            QT_TR_NOOP("\t\t%1\n")
#define IDS_PRE_TIMEOUT_FORMAT          QT_TR_NOOP("Time Remaining: %us")
#define IDS_POST_TIMEOUT_FORMAT         QT_TR_NOOP("Time Remaining: Expired")
#define IDS_REQUEST_FORMAT_WITHOUT_LOCATION QT_TR_NOOP("Do you accept the request for the transfer of rights from:\n\t %s/%s")
#define IDS_ERROR_MESSAGE               QT_TR_NOOP("An error occured while attempting to display an application message box.\nThis is an unrecoverable error. Check log file for further details.\nControl Station will now exit.")
#define IDS_CHANGE_DISPLAY_MODE         QT_TR_NOOP("change display mode")
