using Dottest.Framework;
using NUnit.Framework;
using OPCSampleGrpConfig.DotTest.Factories.View;
using OPCSampleGrpConfig.View;
using STEE.ISCS.MVC;
using System;

namespace OPCSampleGrpConfig.DotTest.View
{
    [TestFixture()]
    public class OPCSampleGrpConfigViewFactoryTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/YnOSA", "/pdqmQ")]
        public void TestCreateView01()
        {
            OPCSampleGrpConfigViewFactory oPCSampleGrpConfigViewFactory = OPCSampleGrpConfigViewFactoryFactory.CreateOPCSampleGrpConfigViewFactory01();
            string type = string.Empty;
            string id = string.Empty;
            IView view = oPCSampleGrpConfigViewFactory.CreateView(type, id);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+AHF8g", "/ovHDg")]
        public void TestOPCSampleGrpConfigViewFactoryConstructor01()
        {
            OPCSampleGrpConfigViewFactory oPCSampleGrpConfigViewFactory = new OPCSampleGrpConfigViewFactory();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]        
        [TestAuthor("user")]
        [Test]
        [HashCode("/YnOSA", "/pdqmQ")]
        public void TestCreateView02()
        {
            OPCSampleGrpConfigViewFactory oPCSampleGrpConfigViewFactory = OPCSampleGrpConfigViewFactoryFactory.CreateOPCSampleGrpConfigViewFactory01();
            string type = OPCSampleGrpConfigStart.OPCSAMPLEGRPCONFIGSTARTFRM;
            string id = string.Empty;
            //Test Procedure Call
            IView view = oPCSampleGrpConfigViewFactory.CreateView(type, id);
            //Post Condition Check
            Assert.IsInstanceOfType(typeof(OPCSampleGrpConfigStart), view);
            Assert.IsNotNull(view.getController());

            //test2
            type = OPCDataSelector.OPCDATASELECTORFRM;
            id = string.Empty;
            //Test Procedure Call
            TrendingHelper.ConfigureFileHelper.GetInstance().init();
            DAO.Trending.Common.DBConnectionStrings.GetInstance().AddConnectionString(TrendingHelper.ConfigureFileHelper.GetInstance().ConnectionStringConfig);
            view = oPCSampleGrpConfigViewFactory.CreateView(type, id);
            //Post Condition Check
            Assert.IsInstanceOfType(typeof(OPCSampleGrpConfig.View.OPCDataSelector), view);
            Assert.IsNotNull(view.getController());
        }



    }
}
