using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.MulLanguage;

namespace STEE.ISCS.MulLanguage.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class MessageBoxDialogFactory
    {
        [ObjectFactoryMethod]
        [HashCode("/pIgBw", "/KhahA")]
        public static MessageBoxDialog CreateMessageBoxDialog01()
        {
            MessageBoxDialog messageBoxDialog = new MessageBoxDialog();
            return messageBoxDialog;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateMessageBoxDialog01()
        {
            MessageBoxDialog messageBoxDialog = CreateMessageBoxDialog01();
            Assert.IsNotNull(messageBoxDialog);
        }

    }
}
