using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.MulLanguage;

namespace STEE.ISCS.MulLanguage.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class StringHelperFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+6PHpw", "+tJRCQ")]
        public static StringHelper CreateStringHelper01()
        {
            StringHelper stringHelper = StringHelper.GetInstance();
            return stringHelper;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateStringHelper01()
        {
            StringHelper stringHelper = CreateStringHelper01();
            Assert.IsNotNull(stringHelper);
        }

    }
}
