using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCData;
using OPCTrendLib.OPCHeader;
using OPCTrendLib.OPCDataInterface;


namespace DotTest.OPCTrendLib.OPCData
{
    [TestFixture()]
    public class OPCPropertyItemTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCPropertyItemString01()
        {
            OPCPropertyItem opcPropertyItem = new OPCPropertyItem();
            opcPropertyItem.Error = 0;
            opcPropertyItem.newItemID = "NewID";
            opcPropertyItem.PropertyID = 1;
            //Test Procedure Call
            string result = opcPropertyItem.ToString();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCPropertyItemString02()
        {
            OPCPropertyItem opcPropertyItem = new OPCPropertyItem();
            opcPropertyItem.Error = 1;
            opcPropertyItem.newItemID = "NewID";
            opcPropertyItem.PropertyID = 1;
            //Test Procedure Call
            string result = opcPropertyItem.ToString();
        }
    }
}

