using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib.OPCHeader;

namespace DotTest.OPCTrendLib.OPCHeader
{
    [TestFixture()]
    public class OPCServerListTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCServerList01()
        {
            //Test Procedure Call
            OPCServerList opcserverList = new OPCServerList();            
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServerData01()
        {
            //testing
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServerData(out serverslist);
        }


        [ExpectedException(typeof(System.Runtime.InteropServices.COMException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer01()
        {
            //testing -- same as code
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(new System.Guid("63D5F432-CFE4-11d1-B2C8-0060083BA1FB"), out serverslist);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer02()
        {
            //testing --- empty guid
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(System.Guid.Empty, out serverslist);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer03()
        {
            //testing --- New guid
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(System.Guid.NewGuid(), out serverslist);
        }

        [ExpectedException(typeof(System.Runtime.InteropServices.COMException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer04()
        {
            //testing --- Error with EnumClassesOfCategories
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(System.Guid.NewGuid(), out serverslist);
        }

        [ExpectedException(typeof(System.Runtime.InteropServices.COMException))]
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer05()
        {
            //testing --- Error with EnumClassesOfCategories
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(System.Guid.NewGuid(), out serverslist);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestListAllServer06()
        {
            //testing --- Error with EnumClassesOfCategories
            OPCServerList opcserverList = new OPCServerList();
            OPCServers[] serverslist;
            //Test Procedure Call
            opcserverList.ListAllServer(System.Guid.NewGuid(), out serverslist);
        }


    }
}
