#pragma once
#include <QTextCodec>
#include <QTranslator>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QPlainTextEdit>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>
#include <QVariant>
#include <QMessageBox>
#include <boost/bind.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string/split.hpp>
#include <vector>
#include <sstream>
#include <string>
#include <map>
#include <list>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cstdio>
