using Dottest.Framework;
using NUnit.Framework;
using STEE.ISCS.Log;

namespace STEE.ISCS.Log.DotTest.Factories
{
    [TestFixture(), ObjectFactoryType()]
    public class LogLevelFactory
    {
        [ObjectFactoryMethod]
        [HashCode("/4MZdQ", "+2X9WA")]
        public static LogLevel CreateLogLevel01()
        {
            // TODO: Skeleton of the object factory method
            LogLevel logLevel = new LogLevel();
            return logLevel;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateLogLevel01()
        {
            LogLevel logLevel = CreateLogLevel01();
        }

    }
}
