using Dottest.Framework;
using NUnit.Framework;
using OPCDataLogger;
using OPCDataLogger.DotTest.Factories;
using Dottest.Framework.RecordState;
using System;

namespace OPCDataLogger.DotTest
{
    [TestFixture()]
    public class CheckConfigVarsTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/JxT+w", "/C4lIg")]
        public void TestUpdateToDisableOPCDTSmplFlag01()
        {
            CheckConfigVars checkConfigVars = CheckConfigVarsFactory.CreateCheckConfigVars01();
            checkConfigVars.UpdateToDisableOPCDTSmplFlag();
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/2LNmg", "/Oxl1w")]
        public void TestGetOPCDTSmplFlagValue01()
        {
            CheckConfigVars checkConfigVars = CheckConfigVarsFactory.CreateCheckConfigVars01();
            string str = checkConfigVars.GetOPCDTSmplFlagValue();
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record(str);
            recorder.FinishRecording();
            #endregion
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/qBB8w", "/7QZ5g")]
        public void TestCheckConfigVarsConstructor01()
        {
            CheckConfigVars checkConfigVars = new CheckConfigVars();
        }

    }
}
