using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCDataLogger;
using System;
using System.Windows.Forms;
using OPCDataLogger.DotTest.Factories;

namespace OPCDataLogger.DotTest
{
    [TestFixture()]
    public class OPCDataLoggerTests
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/MLfhA", "/e6dzA")]
        public void TestOPCDataLoggerConstructor01()
        {
            //Test1 ---- Single Process
            //Test Procedure Call
            OPCDataLogger oPCDataLogger = new OPCDataLogger();
            //Post Condition check
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLoggerConstructor02()
        {
            //Test2 ---- Multiple Same Process running
            //Test Procedure Call
            OPCDataLogger oPCDataLogger = new OPCDataLogger();
            //Post Condition check


        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/DVGpQ", "/3S8ew")]
        public void TestDispose01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                bool disposing = true;
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.SetField("components", new System.ComponentModel.Container());
                //Test Procedure Call
                oPCDataLoggerAccessor.Call("Dispose", disposing);  

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+cMfaQ", "+TtytA")]
        public void TestInitializeComponent01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("InitializeComponent");                
            }
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLogger_FormClosed01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("OPCDataLogger_FormClosed",null,null);

            }
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLogger_Resize01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("OPCDataLogger_Resize", null, null);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLogger_Load01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("OPCDataLogger_Load", null, null);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLogger_Paint01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                System.Drawing.Graphics graphics = oPCDataLogger.CreateGraphics();
                PaintEventArgs painte = new PaintEventArgs(graphics, new System.Drawing.Rectangle());
                oPCDataLoggerAccessor.Call("OPCDataLogger_Paint", null, painte);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestOPCDataLogger_FormClosing01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                FormClosingEventArgs e = new FormClosingEventArgs(CloseReason.None, false);
                oPCDataLoggerAccessor.Call("OPCDataLogger_FormClosing", null, e);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestcloseApplicationToolStripMenuItem_Click01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("closeApplicationToolStripMenuItem_Click", null, null);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestcloseApplicationToolStripMenuItem_Click02()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("closeApplicationToolStripMenuItem_Click", null, null);

            }
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestRestoreMenuStrip_Click01()
        {
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("RestoreMenuStrip_Click", null, null);

            }
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestRestoreMenuStrip_Click02()
        {
            //test --- exception thrown from RemoveAllItems method
            using (OPCDataLogger oPCDataLogger = OPCDataLoggerFactory.CreateOPCDataLogger01())
            {
                Accessor oPCDataLoggerAccessor = ReflectionAccessor.Wrap(oPCDataLogger);
                oPCDataLoggerAccessor.Call("RestoreMenuStrip_Click", null, null);

            }
        } 
    }
}
