using Dottest.Framework;
using NUnit.Framework;
using System;

namespace OPCDataLogger.DotTest
{
    [TestFixture()]
    class Properties_SettingsTest
    {
        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestSettingsConstructor01()
        {
            Properties.Settings settings = new Properties.Settings();

            //Post Check
            Assert.IsNotNull(settings);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestGetDefault01()
        {

            Properties.Settings defaultsetting = Properties.Settings.Default;

            //Post Check
            Assert.IsNotNull(defaultsetting);
        }
    }
}
