using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class BooleanOrFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+joDTw", "+4WEww")]
        internal static BooleanOr CreateBooleanOr01()
        {
            BooleanOr booleanOr = new BooleanOr();
            booleanOr.ToString();
            return booleanOr;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateBooleanOr01()
        {
            BooleanOr booleanOr = CreateBooleanOr01();
            Assert.IsNotNull(booleanOr);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((OperatorPriority)booleanOr.Priority);
            recorder.FinishRecording();
            #endregion
        }

    }
}
