using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;
using System;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class BooleanAndExecutorFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+MffwQ", "/EyDEQ")]
        internal static BooleanAndExecutor CreateBooleanAndExecutor01()
        {
            BooleanAndExecutor booleanAndExecutor = new BooleanAndExecutor();
            return booleanAndExecutor;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateBooleanAndExecutor01()
        {
            BooleanAndExecutor booleanAndExecutor = CreateBooleanAndExecutor01();
            Assert.IsNotNull(booleanAndExecutor);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((int)ReflectionAccessor.Wrap(booleanAndExecutor).GetProperty("CurrentIndex"));
            recorder.FinishRecording();
            #endregion
        }

    }
}
