using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;
using System;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class BooleanOrExecutorFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+Gdtww", "/tt8pQ")]
        internal static BooleanOrExecutor CreateBooleanOrExecutor01()
        {
            BooleanOrExecutor booleanOrExecutor = new BooleanOrExecutor();
            return booleanOrExecutor;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateBooleanOrExecutor01()
        {
            BooleanOrExecutor booleanOrExecutor = CreateBooleanOrExecutor01();
            Assert.IsNotNull(booleanOrExecutor);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((int)ReflectionAccessor.Wrap(booleanOrExecutor).GetProperty("CurrentIndex"));
            recorder.FinishRecording();
            #endregion
        }

    }
}
