using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class ConditionalOpFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+xJfqg", "+9yCzg")]
        internal static ConditionalOp CreateConditionalOp01()
        {
            ConditionalOp conditionalOp = new ConditionalOp();
            return conditionalOp;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateConditionalOp01()
        {
            ConditionalOp conditionalOp = CreateConditionalOp01();
            Assert.IsNotNull(conditionalOp);
            #region Record State
            ValueRecorder recorder = new ValueRecorder();
            recorder.Record((OperatorPriority)conditionalOp.Priority);
            recorder.FinishRecording();
            #endregion
        }

    }
}
