using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;
//using STEE.ISCS.Log.DotTest.Factories;
using System;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class ConstantFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+oEyHg", "+wMR2g")]
        internal static Constant CreateConstant01()
        {
           // object value1 = LogLevelFactory.CreateLogLevel01();
            Constant constant = new Constant("SAA");
            constant.ToString();
            return constant;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateConstant01()
        {
            Constant constant = CreateConstant01();
            Assert.IsNotNull(constant);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateConstant02()
        {
            Constant constant = new Constant(typeof(string), "Hi");
            System.Type type = constant.Type;
            Assert.IsNotNull(constant);
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateConstant03()
        {
            Constant constant = new Constant(null);
            constant.ToString();
             
        }

    }
}
