using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class ExecutorContextFactory
    {
        [ObjectFactoryMethod]
        [HashCode("/0IyTw", "+ve+3g")]
        public static ExecutorContext CreateExecutorContext01()
        {
            ExecutorContext executorContext = new Evaluator();
            string tag = (string)executorContext.Tag;
            executorContext.Tag = tag;
            return executorContext;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateExecutorContext01()
        {
            ExecutorContext executorContext = CreateExecutorContext01();
            Assert.IsNotNull(executorContext);
        }

    }
}
