using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class IVariableHolderFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+rZFNg", "/XL72w")]
        public static IVariableHolder CreateIVariableHolder01()
        {
            IVariableHolder variableHolder = new ParameterVariableHolder();
            return variableHolder;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateIVariableHolder01()
        {
            IVariableHolder variableHolder = CreateIVariableHolder01();
            Assert.IsNotNull(variableHolder);
        }

    }
}
