using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class ParameterVariableHolderFactory
    {
        [ObjectFactoryMethod]
        [HashCode("/ZAXTg", "/XL72w")]
        public static ParameterVariableHolder CreateParameterVariableHolder01()
        {
            ParameterVariableHolder parameterVariableHolder = new ParameterVariableHolder();
            return parameterVariableHolder;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateParameterVariableHolder01()
        {
            ParameterVariableHolder parameterVariableHolder = CreateParameterVariableHolder01();
            Assert.IsNotNull(parameterVariableHolder);
        }

    }
}
