using Dottest.Framework;
using NUnit.Framework;
using OPCTrendLib;
using System;

namespace DotTest.Factories.OPCTrendLib
{
    [TestFixture(), ObjectFactoryType()]
    public class ScannerFactory
    {
        [ObjectFactoryMethod]
        [HashCode("+1wsQg", "+GyusA")]
        internal static Scanner CreateScanner01()
        {
            string text = string.Empty;
            Scanner scanner = new Scanner(text);
            return scanner;
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        public void TestCreateScanner01()
        {
            Scanner scanner = CreateScanner01();
            Assert.IsNotNull(scanner);
        }

    }
}
