#ifndef STRING_RESOURCE_H_INCLUDED
#define STRING_RESOURCE_H_INCLUDED


//#define ID_APP_ABOUT 57664							//"Display program information, version number and copyright\nAbout"
//#define ID_APP_EXIT 57665							//"Quit the application\nExit"
//#define IDS_LOCATION_STATUS 57666					//	"Loading Location rights ..."
//#define IDS_SUBSYSTEM_STATUS 57667					//	"Loading Subsystem rights ..."
#define STRING_ID_DUTY_MANAGER_0000 6214			//		"During initialise Subsystem DutyGrid, no session persisted in DB"
#define STRING_ID_DUTY_MANAGER_0001 6215			//		"Still failed after retry"
#define STRING_ID_DUTY_MANAGER_0003 6216			//		"No available other sessions."
#define STRING_ID_DUTY_MANAGER_0004 6217			//		"checking the subsystem status..."
#define STRING_ID_DUTY_MANAGER_0005 6218			//		"Rights Manager PS"
#define STRING_ID_DUTY_MANAGER_0006 6219			//		"System-wide delegation"
#define STRING_ID_DUTY_MANAGER_0007 6220			//		"RightsManager"
#define STRING_ID_DUTY_MANAGER_0008 6221			//		"Failed to retrieve duty information. Please retry later. The dialog will be closed!"
#define STRING_ID_DUTY_MANAGER_0009 6222			//		"the DutyAgent at location "
#define STRING_ID_DUTY_MANAGER_0010 6223			//		" is just recover from broken down. If you have some operation related to that location rights. Please close the Rights manager ane reopen it."
#define STRING_ID_DUTY_MANAGER_0011 6224			//		" One of the DutyAgent is just recover from broken down. If you have some operation related to the rights. Please close the Rihgts manager ane reopen it."
#define STRING_ID_DUTY_MANAGER_0012 6225			//		"Take location duty"
#define STRING_ID_DUTY_MANAGER_0013 6226			//		"RightsManager is populating data, please try again later!"


#define 		STRING_ID_DUTY_MANAGER_0014		6227//	"Region"
#define 		STRING_ID_DUTY_MANAGER_0019		6228//	"Location"
#define 		STRING_ID_DUTY_MANAGER_0016		6229//	"Operator"
#define 		STRING_ID_DUTY_MANAGER_0017		6230//	"Profile"
#define 		STRING_ID_DUTY_MANAGER_0018		6231//	"Subsystem"
#define 		STRING_ID_DUTY_MANAGER_0020		6232//	"Servers are busy, Please retry later."
#define 		STRING_ID_DUTY_MANAGER_0021		6233//	"Error while requesting subsystem duty."
#define 		STRING_ID_DUTY_MANAGER_0022		6234//	"No transferable locations."
#define 		STRING_ID_DUTY_MANAGER_0023		6235//	"No transferable regions."
#define 		STRING_ID_DUTY_MANAGER_0024		6236//	"Error while taking location duty."
#define 		STRING_ID_DUTY_MANAGER_0025		6237//	"Error while taking region duty."
#define 		STRING_ID_DUTY_MANAGER_0026		6238//	"Select locations"
#define 		STRING_ID_DUTY_MANAGER_0027		6239//	"No assigned locations."
#define 		STRING_ID_DUTY_MANAGER_0028		6240//	"No assigned regions."
#define 		STRING_ID_DUTY_MANAGER_0029		6241//	"Error while select Session Duty from SelectSesSubDutyDlg."
#define 		STRING_ID_DUTY_MANAGER_0030		6242//	"Error while select Session Duty from SelectSesSubDutyDlg."
#define 		STRING_ID_DUTY_MANAGER_0031		6243//	"Error while updating transferable subsystem list."
#define 		STRING_ID_DUTY_MANAGER_0032		6244//	"Error while updating transferable subsystem list."
#define 		STRING_ID_DUTY_MANAGER_0033		6245//	"Error while updating transferable subsystem list."
#define 		STRING_ID_DUTY_MANAGER_0034		6246//	"No transferable subsystems."
#define 		STRING_ID_DUTY_MANAGER_0035		6247//	"Error while setting subsystem duty grid cell for \r\n subsystem [%1] and region [%2]"
#define 		STRING_ID_DUTY_MANAGER_0036		6248//	"Error while adding subsystem to subsystem duty grid."
#define 		STRING_ID_DUTY_MANAGER_0037		6249//	"Error while adding region to subsystem duty grid."
#define 		STRING_ID_DUTY_MANAGER_0038		6250//	"Selected Session:  Operator: [%1],    Profile: [%2],    Location: [%3],    Workstation: [%4],    SessionId: [%5]"
#define 		STRING_ID_DUTY_MANAGER_0039		6251//	"Error while releasing control from central operators."
#define 		STRING_ID_DUTY_MANAGER_0040		6252//	"RightsManager is populating data, please try again later!"
#define 		STRING_ID_DUTY_MANAGER_0041		6253//	"Error while activating duty transfer dialog."
#define 		STRING_ID_DUTY_MANAGER_0042		6254//	"Servers are busy, Please retry later."
#define 		STRING_ID_DUTY_MANAGER_0043		6255//	"Error while activating duty transfer dialog."
#define 		STRING_ID_DUTY_MANAGER_0045		6256//	"Error while activating duty transfer dialog."
#define 		STRING_ID_DUTY_MANAGER_0046		6257//	"Error while adding region to subsystem duty grid."
#define 		STRING_ID_DUTY_MANAGER_0047		6258//	"Error while activating duty request dialog."
#define 		STRING_ID_DUTY_MANAGER_0048		6259//	"Error while activating duty request dialog."
#define 		STRING_ID_DUTY_MANAGER_0049		6260//	"Error while requesting duty for all subsystems."
#define 		STRING_ID_DUTY_MANAGER_0050		6261//	"Servers are busy, Please retry later."
#define 		STRING_ID_DUTY_MANAGER_0051		6262//	"RightsManager is populating data, please try again later!"
#define 		STRING_ID_DUTY_MANAGER_0052		6263//	"Workstation"




#endif
