using Dottest.Framework;
using Dottest.Framework.RecordState;
using NUnit.Framework;
using STEE.ISCS.GenericGUI;
using System;
using STEE.ISCS.MVC;
using OPCSampleGrpConfig.DotTest.Factories.Controller;
using System.Windows.Forms;
using STEE.ISCS.GenericGUI.Properties;
//using TrendViewer.Controller;

namespace STEE.ISCS.GenericGUI.DotTest
{
    [TestFixture()]
    public class BaseFormTests
    {
        private BaseForm baseForm;

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            baseForm = new BaseForm();
        }

        [Test]
        public void TestSetting()
        {
            Settings sett = Settings.Default;
        }

        [Test]
        public void TestResources()
        {
            Resources re = new Resources();
            global::System.Globalization.CultureInfo info = Resources.Culture;
            Resources.Culture = info;

            global::System.Resources.ResourceManager mgr = Resources.ResourceManager;
           // Resources.ResourceManager = mgr;


        }
        [Test]
        public void TestProperties()
        {
            string s = baseForm.ViewID;
            baseForm.ViewID = s;

            s = baseForm.ViewType;
            baseForm.ViewType = s;

            baseForm.PutObject("", null);

        }


        [Test]
        public void TestDestroyView()
        {
            baseForm.DestroyView();
        }

        [Test]
        public void TestHideView()
        {
            baseForm.HideView();
        }

        [Test]
        public void TestShowView()
        {
            baseForm.ShowView(true);
            baseForm.ShowView(false);
        }






        [Test]
        public void TestgetController()
        {
            baseForm.getController();
        }

        [Test]
        public void TestTranslateCaption()
        {
            baseForm.TranslateCaption();
        }



        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/cmPZw", "/OIZBQ")]
        public void TestAttachController01()
        {
            using (IController controller = OPCDataSelectorControllerFactory.CreateOPCDataSelectorController01())
            {
                baseForm.AttachController(controller);
         
            }
        }


        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("+0Pmfg", "/cDnVg")]
        public void TestBaseForm_FormClosed01()
        {
            using (IController controller = OPCDataSelectorControllerFactory.CreateOPCDataSelectorController01())
            {
                baseForm.AttachListener(controller);

            }


            object sender = null; 
            FormClosedEventArgs e = null;
            Accessor baseFormAccessor = ReflectionAccessor.Wrap(baseForm);
            baseFormAccessor.Call("BaseForm_FormClosed", sender, e);
      
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/OneeA", "/mGo+A")]
        public void TestBaseForm_Load01()
        {
            object sender = null;
            EventArgs e = null;
            Accessor baseFormAccessor = ReflectionAccessor.Wrap(baseForm);
            baseFormAccessor.Call("BaseForm_Load", sender, e);
          
        }

        [TestCaseUnverified("Test case not verified")]
        [TestCaseAutogenerated]
        [TestAuthor("user")]
        [Test]
        [HashCode("/KPNbA", "+2ZmOg")]
        public void TestDispose01()
        {
           bool disposing = false;
           Accessor baseFormAccessor = ReflectionAccessor.Wrap(baseForm);
          
            baseFormAccessor.Call("Dispose", disposing);

            disposing = true;
            baseFormAccessor.SetField("components", new System.ComponentModel.Container());

            baseFormAccessor.Call("Dispose", disposing);


        }

    }

}
